name: Action test on Ubuntu

on:
  schedule:
    - cron: "0 2 * * MON-FRI" # Runs at 02:00 UTC
  push:
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/ubuntu_report_minimal.txt
      - uses: GuillaumeFalourd/git-commit-push@main

  ubuntu-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/ubuntu_report_full.txt
      - uses: GuillaumeFalourd/git-commit-push@main
        with:
          email: ${{ github.actor }}[bot]@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: ubuntu full workflow
          target_branch: ubuntu
          files: reports/ubuntu_report_full.txt
          remote_repository: origin
          access_token: ${{ github.token }}
          force: true
          empty: true
          tags: true

  ubuntu-full-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/ubuntu_report_full_remote.txt
      - uses: GuillaumeFalourd/git-commit-push@main
        with:
          email: ${{ github.actor }}[bot]@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: ubuntu full remote workflow
          target_branch: ubuntu
          files: reports/ubuntu_report_full_remote.txt
          remote_repository: https://github.com/GuillaumeFalourd/poc-github-actions
          access_token: ${{ secrets.ACCESS_TOKEN }}
          force: true
          empty: true
          tags: true

  ubuntu-nochanges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/git-commit-push@main
