name: Action test on Ubuntu

on:
  schedule:
    - cron: "0 2 * * *" # Runs at 02:00 UTC everyday
  workflow_dispatch:

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/ubuntu_report_1.txt
      - uses: GuillaumeFalourd/git-commit-push@main

  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/ubuntu_report_2.txt
      - uses: GuillaumeFalourd/git-commit-push@main
        with:
          email: ${{ github.actor }}[bot]@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: ubuntu full workflow
          target_branch: ${{ github.ref }}
          files: reports/ubuntu_report_2.txt
          remote_repository: origin
          access_token: ${{ github.token }}
          force: true
          empty: true
          tags: true