name: Action test on Windows

on:
  schedule:
    - cron: "0 6 * * MON-FRI" # Runs at 06:00 UTC
  push:
  workflow_dispatch:

jobs:
  windows-minimal:
    runs-on: windows-latest
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/windows_report_minimal.txt
      - uses: GuillaumeFalourd/git-commit-push@main

  windows-full:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/windows_report_full.txt
      - uses: GuillaumeFalourd/git-commit-push@main
        with:
          email: ${{ github.actor }}[bot]@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: windows full workflow
          target_branch: windows
          files: reports/windows_report_full.txt
          remote_repository: origin
          access_token: ${{ github.token }}
          force: true
          empty: true
          tags: true

  windows-full-remote:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: date > reports/windows_report_full_remote.txt
      - uses: GuillaumeFalourd/git-commit-push@main
        with:
          email: ${{ github.actor }}[bot]@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: windows full remote workflow
          target_branch: windows
          files: reports/windows_report_full_remote.txt
          remote_repository: https://github.com/GuillaumeFalourd/poc-github-actions
          access_token: ${{ secrets.ACCESS_TOKEN }}
          force: true
          empty: true
          tags: true

  windows-nochanges:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/git-commit-push@main
